use quizdb;
DROP TABLE IF EXISTS quizz;
CREATE TABLE quizz (
    id INT PRIMARY KEY  NOT NULL AUTO_INCREMENT,
    auteur varchar (255),
    date varchar (255),
    categorie varchar (255),
    question TEXT NOT NULL,
    a TEXT NOT NULL,
    b TEXT NOT NULL,
    c TEXT NOT NULL,
    d TEXT NOT NULL,
    correct CHAR(1) NOT NULL
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Insertion des questions sur l'education au Senegal
INSERT INTO quizz (auteur, date,categorie, question, a, b, c, d, correct) VALUES 
("talla",
"22 juin 2024",
 "histoire",
 "Quelle est la langue principalement utilisee dans l'education formelle au Senegal ?", 
    "Wolof", 
    "Français", 
    "Peul", 
    "Serère", 
    "b"),
("talla",
"22 juin 2024",
 "histoire",
 "Quel est le niveau d'education obligatoire au Senegal ?", 
    "Primaire", 
    "Secondaire", 
    "Primaire et secondaire", 
    "Secondaire et superieur", 
    "c"),
("talla",
"22 juin 2024",
 "histoire",
 "Quel est le nom de l'universite la plus ancienne et la plus grande du Senegal, situee a Dakar ?", 
    "Universite Cheikh Anta Diop", 
    "Universite Gaston Berger", 
    "Universite Alioune Diop de Bambey", 
    "Universite Assane Seck de Ziguinchor", 
    "a"),
("talla",
"22 juin 2024",
 "histoire",
 "Quelle est la duree typique des etudes universitaires pour obtenir une licence au Senegal ?", 
    "3 ans", 
    "4 ans", 
    "5 ans", 
    "6 ans", 
    "b"),
("talla",
"22 juin 2024",
 "histoire",
 "Quel est le pourcentage approximatif d'alphabetisation au Senegal ?", 
    "50%", 
    "60%", 
    "70%", 
    "80%", 
    "c"),
("talla",
"22 juin 2024",
 "histoire",
 "Quel est le nom du système d'examen national a la fin de l'enseignement secondaire au Senegal ?", 
    "Baccalaureat", 
    "Certificat de Fin d'etudes elementaires", 
    "Diplôme d'etudes Approfondies", 
    "Certificat d'Aptitude Professionnelle", 
    "a"),
("talla",
"22 juin 2024",
 "histoire",
 "Quelle est la principale ville universitaire situee dans la region de Saint-Louis ?", 
    "Dakar", 
    "Ziguinchor", 
    "Thiès", 
    "Saint-Louis", 
    "d"),
("talla",
"22 juin 2024",
 "histoire",
 "Quelle est l'organisation responsable de l'administration de l'education au Senegal ?", 
    "Ministère de l'education Nationale", 
    "Agence Nationale de l'Enseignement Superieur", 
    "Conseil National de l'education", 
    "Commission Nationale de l'UNESCO", 
    "a"),
("talla",
"22 juin 2024",
 "histoire",
 "Quel est le nom du programme senegalais visant a promouvoir l'accès a l'education primaire pour tous ?", 
    "Programme d'Alphabetisation Acceleree", 
    "Programme d'education Pour Tous", 
    "Programme de Renforcement de l'education", 
    "Programme de Lutte Contre l'Analphabetisme", 
    "b"),
("talla",
"22 juin 2024",
 "histoire",
 "Quel est le nombre approximatif d'universites publiques au Senegal ?", 
    "3", 
    "5", 
    "7", 
    "10", 
    "c");
